/**
 * Code Generator for creating fix proposals using Kiro CLI
 */

import { spawn } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';
import { Diagnosis } from './ai-diagnostician';

/**
 * File change information
 */
export interface FileChange {
  path: string;
  oldContent: string;
  newContent: string;
  diff: string;
}

/**
 * Fix proposal generated by Kiro CLI
 */
export interface FixProposal {
  incidentId: string;
  diagnosisId: string;
  changes: FileChange[];
  description: string;
  testCases?: string[];
  timestamp: number;
}

/**
 * Code Generator configuration
 */
export interface CodeGeneratorConfig {
  kiroCliPath?: string; // Path to Kiro CLI executable
  workingDirectory?: string; // Working directory for code generation
  timeout?: number; // Timeout in milliseconds, default: 120000 (2 minutes)
}

/**
 * Code Generator class for creating fix proposals
 */
export class CodeGenerator {
  private config: CodeGeneratorConfig;
  private readonly DEFAULT_TIMEOUT = 120000; // 2 minutes
  private readonly DEFAULT_KIRO_PATH = 'kiro'; // Assume kiro is in PATH

  constructor(config: CodeGeneratorConfig = {}) {
    this.config = {
      kiroCliPath: config.kiroCliPath || this.DEFAULT_KIRO_PATH,
      workingDirectory: config.workingDirectory || process.cwd(),
      timeout: config.timeout || this.DEFAULT_TIMEOUT,
    };
  }

  /**
   * Generate a fix proposal for a diagnosis
   */
  async generateFix(diagnosis: Diagnosis): Promise<FixProposal> {
    try {
      // Create context file for Kiro CLI
      const contextPath = await this.createContextFile(diagnosis);

      // Invoke Kiro CLI
      const kiroOutput = await this.invokeKiroCLI(diagnosis, contextPath);

      // Parse Kiro CLI output
      const fixProposal = await this.parseKiroOutput(diagnosis, kiroOutput);

      // Validate the generated code
      const isValid = await this.validateFix(fixProposal);
      
      if (!isValid) {
        throw new Error('Generated code contains syntax errors');
      }

      // Clean up context file
      await this.cleanupContextFile(contextPath);

      return fixProposal;

    } catch (error) {
      console.error('Code generation failed:', error instanceof Error ? error.message : 'Unknown error');
      throw error;
    }
  }

  /**
   * Create context file for Kiro CLI
   */
  private async createContextFile(diagnosis: Diagnosis): Promise<string> {
    const context = {
      incidentId: diagnosis.incidentId,
      rootCause: diagnosis.rootCause,
      explanation: diagnosis.explanation,
      category: diagnosis.category,
      codeLocation: diagnosis.codeLocation,
      suggestedFix: diagnosis.suggestedFix,
      confidence: diagnosis.confidence,
    };

    const contextPath = path.join(
      this.config.workingDirectory!,
      `.vigilai-context-${diagnosis.incidentId}.json`
    );

    await fs.promises.writeFile(contextPath, JSON.stringify(context, null, 2), 'utf-8');

    return contextPath;
  }

  /**
   * Invoke Kiro CLI to generate fix
   */
  private async invokeKiroCLI(diagnosis: Diagnosis, contextPath: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const args = [
        'generate',
        'fix',
        '--diagnosis', diagnosis.rootCause,
        '--context', contextPath,
      ];

      // Add file path if available
      if (diagnosis.codeLocation?.file) {
        args.push('--files', diagnosis.codeLocation.file);
      }

      const kiro = spawn(this.config.kiroCliPath!, args, {
        cwd: this.config.workingDirectory,
        timeout: this.config.timeout,
      });

      let stdout = '';
      let stderr = '';

      kiro.stdout.on('data', (data) => {
        stdout += data.toString();
      });

      kiro.stderr.on('data', (data) => {
        stderr += data.toString();
      });

      kiro.on('close', (code) => {
        if (code === 0) {
          resolve(stdout);
        } else {
          reject(new Error(`Kiro CLI exited with code ${code}: ${stderr}`));
        }
      });

      kiro.on('error', (error) => {
        reject(new Error(`Failed to spawn Kiro CLI: ${error.message}`));
      });
    });
  }

  /**
   * Parse Kiro CLI output into FixProposal
   */
  private async parseKiroOutput(diagnosis: Diagnosis, output: string): Promise<FixProposal> {
    try {
      // Try to parse JSON output from Kiro CLI
      const jsonMatch = output.match(/```json\s*([\s\S]*?)\s*```/) || 
                       output.match(/\{[\s\S]*"changes"[\s\S]*\}/);
      
      if (jsonMatch) {
        const jsonStr = jsonMatch[1] || jsonMatch[0];
        const parsed = JSON.parse(jsonStr);

        return {
          incidentId: diagnosis.incidentId,
          diagnosisId: diagnosis.incidentId, // Use incident ID as diagnosis ID
          changes: parsed.changes || [],
          description: parsed.description || 'Fix generated by Kiro CLI',
          testCases: parsed.testCases,
          timestamp: Date.now(),
        };
      }

      // If no structured output, create a basic fix proposal
      return {
        incidentId: diagnosis.incidentId,
        diagnosisId: diagnosis.incidentId,
        changes: [],
        description: 'Kiro CLI output could not be parsed. Manual fix required.',
        timestamp: Date.now(),
      };

    } catch (error) {
      console.error('Failed to parse Kiro output:', error);
      throw new Error('Failed to parse Kiro CLI output');
    }
  }

  /**
   * Validate generated code for syntax errors
   */
  private async validateFix(fixProposal: FixProposal): Promise<boolean> {
    try {
      // For each file change, validate syntax
      for (const change of fixProposal.changes) {
        const ext = path.extname(change.path);

        if (ext === '.ts' || ext === '.tsx' || ext === '.js' || ext === '.jsx') {
          // Validate TypeScript/JavaScript syntax
          await this.validateTypeScript(change.newContent);
        } else if (ext === '.py') {
          // Validate Python syntax
          await this.validatePython(change.newContent);
        }
        // Add more language validators as needed
      }

      return true;

    } catch (error) {
      console.error('Validation failed:', error);
      return false;
    }
  }

  /**
   * Validate TypeScript/JavaScript syntax
   */
  private async validateTypeScript(code: string): Promise<void> {
    // Basic syntax check - try to parse as JavaScript
    try {
      // Use Function constructor to check for syntax errors
      new Function(code);
    } catch (error) {
      throw new Error(`TypeScript/JavaScript syntax error: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Validate Python syntax
   */
  private async validatePython(code: string): Promise<void> {
    return new Promise((resolve, reject) => {
      // Use Python's compile function to check syntax
      const python = spawn('python', ['-m', 'py_compile', '-'], {
        timeout: 5000,
      });

      python.stdin.write(code);
      python.stdin.end();

      let stderr = '';

      python.stderr.on('data', (data) => {
        stderr += data.toString();
      });

      python.on('close', (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(new Error(`Python syntax error: ${stderr}`));
        }
      });

      python.on('error', (error) => {
        // If python is not available, skip validation
        console.warn('Python not available for syntax validation');
        resolve();
      });
    });
  }

  /**
   * Clean up temporary context file
   */
  private async cleanupContextFile(contextPath: string): Promise<void> {
    try {
      await fs.promises.unlink(contextPath);
    } catch (error) {
      // Ignore cleanup errors
      console.warn('Failed to cleanup context file:', error);
    }
  }
}
