"""Code Generator for creating fix proposals using Kiro CLI"""

import json
import os
import subprocess
import tempfile
import time
import ast
from typing import List, Optional, Dict, Any
from dataclasses import dataclass
from .ai_diagnostician import Diagnosis


@dataclass
class FileChange:
    """File change information"""
    path: str
    old_content: str
    new_content: str
    diff: str


@dataclass
class FixProposal:
    """Fix proposal generated by Kiro CLI"""
    incident_id: str
    diagnosis_id: str
    changes: List[FileChange]
    description: str
    timestamp: int
    test_cases: Optional[List[str]] = None


class CodeGenerator:
    """Code Generator class for creating fix proposals"""
    
    DEFAULT_TIMEOUT = 120  # 2 minutes
    DEFAULT_KIRO_PATH = 'kiro'  # Assume kiro is in PATH
    
    def __init__(
        self,
        kiro_cli_path: Optional[str] = None,
        working_directory: Optional[str] = None,
        timeout: Optional[int] = None
    ):
        self.kiro_cli_path = kiro_cli_path or self.DEFAULT_KIRO_PATH
        self.working_directory = working_directory or os.getcwd()
        self.timeout = timeout or self.DEFAULT_TIMEOUT
    
    def generate_fix(self, diagnosis: Diagnosis) -> FixProposal:
        """Generate a fix proposal for a diagnosis"""
        try:
            # Create context file for Kiro CLI
            context_path = self._create_context_file(diagnosis)
            
            # Invoke Kiro CLI
            kiro_output = self._invoke_kiro_cli(diagnosis, context_path)
            
            # Parse Kiro CLI output
            fix_proposal = self._parse_kiro_output(diagnosis, kiro_output)
            
            # Validate the generated code
            is_valid = self._validate_fix(fix_proposal)
            
            if not is_valid:
                raise ValueError('Generated code contains syntax errors')
            
            # Clean up context file
            self._cleanup_context_file(context_path)
            
            return fix_proposal
            
        except Exception as e:
            print(f"Code generation failed: {str(e)}")
            raise
    
    def _create_context_file(self, diagnosis: Diagnosis) -> str:
        """Create context file for Kiro CLI"""
        context = {
            'incidentId': diagnosis.incident_id,
            'rootCause': diagnosis.root_cause,
            'explanation': diagnosis.explanation,
            'category': diagnosis.category,
            'codeLocation': {
                'file': diagnosis.code_location.file,
                'line': diagnosis.code_location.line,
                'function': diagnosis.code_location.function,
            } if diagnosis.code_location else None,
            'suggestedFix': diagnosis.suggested_fix,
            'confidence': diagnosis.confidence,
        }
        
        context_path = os.path.join(
            self.working_directory,
            f'.vigilai-context-{diagnosis.incident_id}.json'
        )
        
        with open(context_path, 'w', encoding='utf-8') as f:
            json.dump(context, f, indent=2)
        
        return context_path
    
    def _invoke_kiro_cli(self, diagnosis: Diagnosis, context_path: str) -> str:
        """Invoke Kiro CLI to generate fix"""
        args = [
            self.kiro_cli_path,
            'generate',
            'fix',
            '--diagnosis', diagnosis.root_cause,
            '--context', context_path,
        ]
        
        # Add file path if available
        if diagnosis.code_location and diagnosis.code_location.file:
            args.extend(['--files', diagnosis.code_location.file])
        
        try:
            result = subprocess.run(
                args,
                cwd=self.working_directory,
                timeout=self.timeout,
                capture_output=True,
                text=True,
                check=True
            )
            
            return result.stdout
            
        except subprocess.TimeoutExpired:
            raise TimeoutError(f'Kiro CLI timed out after {self.timeout} seconds')
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f'Kiro CLI exited with code {e.returncode}: {e.stderr}')
        except FileNotFoundError:
            raise FileNotFoundError(f'Kiro CLI not found at: {self.kiro_cli_path}')
    
    def _parse_kiro_output(self, diagnosis: Diagnosis, output: str) -> FixProposal:
        """Parse Kiro CLI output into FixProposal"""
        try:
            # Try to parse JSON output from Kiro CLI
            import re
            json_match = re.search(r'```json\s*([\s\S]*?)\s*```', output) or \
                        re.search(r'\{[\s\S]*"changes"[\s\S]*\}', output)
            
            if json_match:
                json_str = json_match.group(1) if json_match.lastindex else json_match.group(0)
                parsed = json.loads(json_str)
                
                # Convert changes to FileChange objects
                changes = []
                for change in parsed.get('changes', []):
                    changes.append(FileChange(
                        path=change.get('path', ''),
                        old_content=change.get('oldContent', ''),
                        new_content=change.get('newContent', ''),
                        diff=change.get('diff', '')
                    ))
                
                return FixProposal(
                    incident_id=diagnosis.incident_id,
                    diagnosis_id=diagnosis.incident_id,  # Use incident ID as diagnosis ID
                    changes=changes,
                    description=parsed.get('description', 'Fix generated by Kiro CLI'),
                    test_cases=parsed.get('testCases'),
                    timestamp=int(time.time() * 1000)
                )
            
            # If no structured output, create a basic fix proposal
            return FixProposal(
                incident_id=diagnosis.incident_id,
                diagnosis_id=diagnosis.incident_id,
                changes=[],
                description='Kiro CLI output could not be parsed. Manual fix required.',
                timestamp=int(time.time() * 1000)
            )
            
        except Exception as e:
            print(f"Failed to parse Kiro output: {str(e)}")
            raise ValueError('Failed to parse Kiro CLI output')
    
    def _validate_fix(self, fix_proposal: FixProposal) -> bool:
        """Validate generated code for syntax errors"""
        try:
            # For each file change, validate syntax
            for change in fix_proposal.changes:
                ext = os.path.splitext(change.path)[1]
                
                if ext == '.py':
                    # Validate Python syntax
                    self._validate_python(change.new_content)
                elif ext in ['.ts', '.tsx', '.js', '.jsx']:
                    # For TypeScript/JavaScript, we'd need Node.js
                    # Skip validation for now or implement if needed
                    pass
                # Add more language validators as needed
            
            return True
            
        except Exception as e:
            print(f"Validation failed: {str(e)}")
            return False
    
    def _validate_python(self, code: str) -> None:
        """Validate Python syntax"""
        try:
            ast.parse(code)
        except SyntaxError as e:
            raise SyntaxError(f'Python syntax error: {str(e)}')
    
    def _cleanup_context_file(self, context_path: str) -> None:
        """Clean up temporary context file"""
        try:
            os.unlink(context_path)
        except Exception as e:
            # Ignore cleanup errors
            print(f"Failed to cleanup context file: {str(e)}")
